version: '3.3'

services:
  nginx:
    image: nginx:inception
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443" # HTTPS
    restart: always
  wordpress:
    image: wordpress:inception
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
    restart: always
  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: always


networks:
  inception:
    driver: bridge

volumes:
  wordpress_vol:
  mariadb_vol: