version: '3.3'

services:
  nginx:
    image: nginx:inception
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443" # HTTPS
    restart: always
  wordpress:
    image: wordpress:inception
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      mariadb: 
        condition: service_healthy #da implementare nel container di Mariadb e finchè il servizio non è "healty" wordpress attende
    restart: always
  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mariadb", "--silent"]
      interval: 2s
      timeout: 30s
      retries: 5
      start_period: 2s
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: always


networks:
  inception:
    driver: bridge

volumes:
  wordpress_vol:
  mariadb_vol: